# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:vnote_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create the tables
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 Console so you can view your database in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console