# ===============================
# LIVE TIDB (MYSQL) CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=3C3y5srLmpRKgGk.root
spring.datasource.password=QNyy0g28KcID76IR
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Automatically create the USERS and NOTES tables in the live DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Set the max file size for a single upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Fix for TiDB Cloud Connection Drops
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000